spring:
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      base-url: https://api.openai.com/v1
      chat:
        options:
          model: gpt-4o
        completions-path: /chat/completions
      embedding:
        options:
          model: text-embedding-3-small

    vectorstore:
      chroma:
        client:
          host: http://localhost
          port: 8000
        initialize-schema: true
        collection-name: documents

# Uncomment to enable debug logging for the advisor
#logging:
#  level:
#    org.springframework.ai.chat.client.advisor: DEBUG
