spring:
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      base-url: https://api.openai.com/v1
      chat:
        options:
          model: gpt-4o
        completions-path: /chat/completions
      embedding:
#        provider: openai
        options:
          model: text-embedding-3-small

    vectorstore:
      chroma:
        client:
          host: http://localhost
          port: 8000
        initialize-schema: true
        collection-name: documents

# ------------------------
# Actuator & Prometheus
# ------------------------
management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    prometheus:
      enabled: true

# Uncomment to enable debug logging for the advisor
#logging:
#  level:
#    org.springframework.ai.chat.client.advisor: DEBUG
